/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Jan 18 12:56:44 2018. */

#include "speech_types.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rokid_open_speech_v1_PingPayload_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, rokid_open_speech_v1_PingPayload, req_id, req_id, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, rokid_open_speech_v1_PingPayload, now_tp, req_id, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, rokid_open_speech_v1_PingPayload, req_tp, now_tp, 0),
    PB_FIELD(  4, UINT64  , REQUIRED, STATIC  , OTHER, rokid_open_speech_v1_PingPayload, resp_tp, req_tp, 0),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
