/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Jan 18 12:56:44 2018. */

#include "tts.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rokid_open_speech_v1_TtsRequest_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, rokid_open_speech_v1_TtsRequest, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, rokid_open_speech_v1_TtsRequest, text, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, rokid_open_speech_v1_TtsRequest, declaimer, text, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, rokid_open_speech_v1_TtsRequest, codec, declaimer, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, rokid_open_speech_v1_TtsRequest, sample_rate, codec, 0),
    PB_LAST_FIELD
};

const pb_field_t rokid_open_speech_v1_TtsResponse_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, rokid_open_speech_v1_TtsResponse, id, id, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, rokid_open_speech_v1_TtsResponse, result, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, rokid_open_speech_v1_TtsResponse, text, result, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, CALLBACK, OTHER, rokid_open_speech_v1_TtsResponse, voice, text, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, rokid_open_speech_v1_TtsResponse, finish, voice, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
